# a, b, c = my_tuple
"""
action = 0, at = 0,nopa = False, noaw = False, noat = False, halfpa = False, halfaw = False, pa = 0, aw = 0, fk = 0,
how_many_turn = 0, beginn = 0, reach = 0,schmerz = 0, betäubung = 0, furcht = 0, paralyse = 0, basic_manöver = False, 
special_manöver = False, tp = 0, check_higher_reach= False, enemyat = 0, target = False, talent = '', enemy_talent = '', 
enemy_talent_minus = 0, freie_action = False,enemy_pa = 0, enemy_aw = 0, enemy_patzer = 0, own_patzer = 0, nervös_halten = 0,
half_gs = False
"""

list_for_pre_combat_basic_ability = {
    "Auf Distanz halten 1": {'name': "Auf Distanz halten 1", "basic_manöver": 1, "check_higher_reach": 1,
                             "enemy_at": -1, "target": 1},
    "Auf Distanz halten 2": {'name': "Auf Distanz halten 2", "basic_manöver": 1, "check_higher_reach": 1,
                             "enemy_at": -2, "target": 1},
}


list_for_pre_combat_special_ability = {
    "Hohe Klinge": {'name': "Hohe Klinge", "how_many_turn": 1, "tp": 1, "at": 1, "half_pa": 1, "half_aw": 1,
                    'weapons': ['Fechtwaffen', 'Schwerter', 'Zweihandschwerter']},
    "Vorstoß": {'name': "Vorstoß", "no_pa": 1, "no_aw": 1, "at": 2, "how_many_turn": 1,
                'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Kettenwaffen', 'Raufen', 'Schwerter',
                            'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Improvisierte Vorstoß": {'name': "Improvisierte Vorstoß", "no_pa": 1, "no_aw": 1, "at": 1, "how_many_turn": 1,
                              'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Kettenwaffen', 'Raufen', 'Schwerter',
                                          'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
}

list_for_pre_combat = {
    "Neersand-Stil Parade": {'name': 'Neersand-Stil Parade', "how_many_turn": 1, "pa": 2},
    "Neersand-Stil Angriff": {'name': "Neersand-Stil Angriff", "how_many_turn": 1, "at": 2, "fk": 2},
    "Nervös machen": {'name': "Nervös machen", "free_action": 1, "talent": 'Einschüchtern Provokation',
                      "enemy_talent": 'Einschüchtern widerstehen', "enemy_miscast": 1},
    "Berserkerangriff 1": [{'name': 'Berserkerangriff 1',"at": 1, "pa": -1, "aw": -1, "how_many_turn": 'w6'},
                           {'name': 'Berserkerangriff 1',"betäubung": 1, "how_many_turn": 'w6', "begin": 'w6'}],
    "Berserkerangriff 2": [{'name': "Berserkerangriff 2","at": 2, "pa": -2, "aw": -2, "how_many_turn": 'w6'},
                            {'name': "Berserkerangriff 2","betäubung": 1, "how_many_turn": 'w6', "begin": 'w6'}],
    "Berserkerangriff 3": [{'name': "Berserkerangriff 3","at": 3, "pa": -3, "aw": -3, "how_many_turn": 'w6'},
                            {'name': "Berserkerangriff 3","betäubung": 1, "how_many_turn": 'w6', "begin": 'w6'}],
    "Berserkerangriff 4": [{'name': "Berserkerangriff 4","at": 4, "pa": -4, "aw": -4, "how_many_turn": 'w6'},
                            {'name': "Berserkerangriff 4","betäubung": 1, "how_many_turn": 'w6', "begin": 'w6'}],
    "Verteidigungshaltung": {'name': "Verteidigungshaltung","action": 1, "how_many_turn": 1, "aw": 4, "pa": 4, "no_at": 1,
                             'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Raufen', 'Schilde', 'Schwerter',
                                         'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Improvisierte Verteidigungshaltung": {'name':"Improvisierte Verteidigungshaltung","action": 1, "how_many_turn": 1,
                                           "aw": 2, "pa": 2, "no_at": 1,
                             'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Raufen', 'Schilde', 'Schwerter',
                                         'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
}


list_for_combat_special = {
    "Sturmangriff": {"tp": 2, "at": -2, "half_gs_tp": 1,
                     'weapons': ['Hiebwaffen', 'Schwerter', 'Stangenwaffen', 'Zweihandhiebwaffen',
                                 'Zweihandschwerter']},
}

list_for_combat_basic = {
    'Wuchtschlag 1': {'name': 'Wuchtschlag 1', 'tp': 2, 'at': -2,
                      'weapons': ['Hiebwaffen', 'Schwerter', 'Kettenwaffen', 'Zweihandhiebwaffen', 'Raufen',
                                  'Stangenwaffen', 'Zweihandschwerter']},
    'Wuchtschlag 2': {'name': 'Wuchtschlag 2', 'tp': 4, 'at': -4,
                      'weapons': ['Hiebwaffen', 'Schwerter', 'Kettenwaffen', 'Zweihandhiebwaffen', 'Raufen',
                                  'Stangenwaffen', 'Zweihandschwerter']},
    'Wuchtschlag 3': {'name': 'Wuchtschlag 3', 'tp': 6, 'at': -6,
                      'weapons': ['Hiebwaffen', 'Schwerter', 'Kettenwaffen', 'Zweihandhiebwaffen', 'Raufen',
                                  'Stangenwaffen', 'Zweihandschwerter']},
    'Improvisierter Wuchtschlag 1': {'name': 'Wuchtschlag 1', 'tp': 2, 'at': -4,
                                     'weapons': ['Hiebwaffen', 'Schwerter', 'Kettenwaffen', 'Zweihandhiebwaffen',
                                                 'Raufen',
                                                 'Stangenwaffen', 'Zweihandschwerter']},
    'Improvisierter Wuchtschlag 2': {'name': 'Wuchtschlag 2', 'tp': 4, 'at': -8,
                                     'weapons': ['Hiebwaffen', 'Schwerter', 'Kettenwaffen', 'Zweihandhiebwaffen',
                                                 'Raufen',
                                                 'Stangenwaffen', 'Zweihandschwerter']},
    'Improvisierter Wuchtschlag 3': {'name': 'Wuchtschlag 3', 'tp': 6, 'at': -12,
                                     'weapons': ['Hiebwaffen', 'Schwerter', 'Kettenwaffen', 'Zweihandhiebwaffen',
                                                 'Raufen',
                                                 'Stangenwaffen', 'Zweihandschwerter']},
    "Finte 1": {'name': 'Finte 1',"at": -1, "enemy_aw": -2, "enemy_pa": -2,
                'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Peitschen', 'Raufen', 'Schwerter', 'Stangenwaffen',
                            'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Finte 2": {'name': 'Finte 2',"at": -2, "enemy_aw": -4, "enemy_pa": -4,
                'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Peitschen', 'Raufen', 'Schwerter', 'Stangenwaffen',
                            'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Finte 3": {'name': 'Finte 3',"at": -3, "enemy_aw": -6, "enemy_pa": -6,
                'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Peitschen', 'Raufen', 'Schwerter', 'Stangenwaffen',
                            'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Improvisierte Finte 1": {'name': 'Improvisierte Finte 1', "at": -2, "enemy_aw": -2, "enemy_pa": -2,
                              'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Peitschen', 'Raufen', 'Schwerter',
                                          'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Improvisierte Finte 2": {'name': 'Improvisierte Finte 2', "at": -4, "enemy_aw": -4, "enemy_pa": -4,
                              'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Peitschen', 'Raufen', 'Schwerter',
                                          'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
    "Improvisierte Finte 3": {'name': 'Improvisierte Finte 3', "at": -6, "enemy_aw": -6, "enemy_pa": -6,
                              'weapons': ['Dolche', 'Fechtwaffen', 'Hiebwaffen', 'Peitschen', 'Raufen', 'Schwerter',
                                          'Stangenwaffen', 'Zweihandhiebwaffen', 'Zweihandschwerter']},
}

dict_of_combattalents = {
    'CT_1': ["Armbrüste", 'Fingerfertigkeit', 'nichts'],
    'CT_2': ["Bögen", 'Fingerfertigkeit', 'nichts'],
    'CT_3': ["Dolche", 'Gewandtheit', 'nichts'],
    'CT_4': ["Fechtwaffen", 'Gewandtheit', 'nichts'],
    'CT_5': ["Hiebwaffen", 'Körperkraft', 'nichts'],
    'CT_6': ["Kettenwaffen", 'Körperkraft', 'nichts'],
    'CT_7': ["Lanzen", 'Körperkraft', 'nichts'],
    'CT_8': ["Peitschen", 'Fingerfertigkeit', 'nichts'],
    'CT_9': ["Raufen", 'Gewandtheit', 'Körperkraft'],
    'CT_10': ["Schilde", 'Körperkraft', 'nichts'],
    'CT_11': ["Schleudern", 'Fingerfertigkeit', 'nichts'],
    'CT_12': ["Schwerter", 'Gewandtheit', 'Körperkraft'],
    'CT_13': ["Stangenwaffen", 'Gewandtheit', 'Körperkraft'],
    'CT_14': ["Wurfwaffen", 'Fingerfertigkeit', 'nichts'],
    'CT_15': ["Zweihandhiebwaffen", 'Körperkraft', 'nichts'],
    'CT_16': ["Zweihandschwerter", 'Körperkraft', 'nichts'],
    'CT_17': ["Feuerspeien", 'Fingerfertigkeit', 'nichts'],
    'CT_18': ["Blasrohre", 'Fingerfertigkeit', 'nichts'],
    'CT_19': ["Diskusse", 'Fingerfertigkeit', 'nichts'],
    'CT_20': ["Fächer", 'Gewandtheit', 'nichts'],
    'CT_21': ["Spießwaffen", 'Körperkraft', 'nichts']
}

liste_zum_suchen = ["Fliegen TAL_1",
                    "Fliegen Kampfmanöver TAL_1",
                    "Fliegen Langstreckenflug TAL_1",
                    "Fliegen Verfolgungsjagden TAL_1",
                    "Fliegen Kunstflug TAL_1",
                    "Gaukeleien TAL_2",
                    "Gaukeleien Jonglieren TAL_2",
                    "Gaukeleien Possenreißen TAL_2",
                    "Gaukeleien Verstecktricks TAL_2",
                    "Gaukeleien Bauchreden TAL_2",
                    "Gaukeleien Feuer schlucken TAL_2",
                    "Gaukeleien Feuerwerk TAL_2",
                    "Klettern TAL_3",
                    "Klettern Baumklettern TAL_3",
                    "Klettern Bergsteigen TAL_3",
                    "Klettern Eisklettern TAL_3",
                    "Klettern Fassadenklettern TAL_3",
                    "Körperbeherrschung TAL_4",
                    "Körperbeherrschung Akrobatik TAL_4",
                    "Körperbeherrschung Balance TAL_4",
                    "Körperbeherrschung Entwinden TAL_4",
                    "Körperbeherrschung Kampfmanöver TAL_4",
                    "Körperbeherrschung Laufen TAL_4",
                    "Körperbeherrschung Springen TAL_4",
                    "Körperbeherrschung Skifahren TAL_4",
                    "Kraftakt TAL_5",
                    "Kraftakt Drücken & Verbiegen TAL_5",
                    "Kraftakt Eintreten & Zertrümmern TAL_5",
                    "Kraftakt Stemmen & Heben TAL_5",
                    "Kraftakt Ziehen & Zerren TAL_5",
                    "Reiten TAL_6",
                    "Reiten Kampfmanöver TAL_6",
                    "Reiten Langstreckenreiten TAL_6",
                    "Reiten Springreiten TAL_6",
                    "Reiten Verfolgungsjagden TAL_6",
                    "Reiten Kunstreiten TAL_6",
                    "Schwimmen TAL_7",
                    "Schwimmen Kampfmanöver TAL_7",
                    "Schwimmen Langstreckenschwimmen TAL_7",
                    "Schwimmen Tauchen TAL_7",
                    "Schwimmen Verfolgungsjagden TAL_7",
                    "Schwimmen Wassertreten TAL_7",
                    "Selbstbeherrschung TAL_8",
                    "Selbstbeherrschung Folter widerstehen TAL_8",
                    "Selbstbeherrschung Handlungsfähigkeit bewahren TAL_8",
                    "Selbstbeherrschung Störungen ignorieren TAL_8",
                    "Singen TAL_9",
                    "Singen Bardenballade TAL_9",
                    "Singen Choral TAL_9",
                    "Singen Chorgesang TAL_9",
                    "Singen Sprechgesang TAL_9",
                    "Singen Operngesang TAL_9",
                    "Singen Zweistimmiger Gesang TAL_9",
                    "Sinnesschärfe TAL_10",
                    "Sinnesschärfe Hinterhalt entdecken TAL_10",
                    "Sinnesschärfe Suchen TAL_10",
                    "Sinnesschärfe Wahrnehmen TAL_10",
                    "Sinnesschärfe Lippenlesen TAL_10",
                    "Sinnesschärfe Magiegespür TAL_10",
                    "Sinnesschärfe Gespür für das Böse TAL_10",
                    "Sinnesschärfe Fuchssinn TAL_10",
                    "Tanzen TAL_11",
                    "Tanzen Dorftanz TAL_11",
                    "Tanzen Exotischer Tanz TAL_11",
                    "Tanzen Hoftanz TAL_11",
                    "Tanzen Kulttanz TAL_11",
                    "Taschendiebstahl TAL_12",
                    "Taschendiebstahl Ablenkungen TAL_12",
                    "Taschendiebstahl Person bestehlen TAL_12",
                    "Taschendiebstahl Gegenstand entwenden TAL_12",
                    "Taschendiebstahl Zustecken TAL_12",
                    "Verbergen TAL_13",
                    "Verbergen Gegenstände verbergen TAL_13",
                    "Verbergen Schleichen TAL_13",
                    "Verbergen Sich verstecken TAL_13",
                    "Zechen TAL_14",
                    "Zechen Vermeidung von Betäubung durch Rauschmittel TAL_14",
                    "Zechen Vermeidung von Schmerz durch Rauschmittel TAL_14",
                    "Zechen Vermeidung von Verwirrung durch Rauschmittel TAL_14",
                    "Bekehren & Überzeugen TAL_15",
                    "Bekehren & Überzeugen Diskussionsführung TAL_15",
                    "Bekehren & Überzeugen Einzelgespräch TAL_15",
                    "Bekehren & Überzeugen Öffentliche Rede TAL_15",
                    "Bekehren & Überzeugen Hetzschriften TAL_15",
                    "Betören TAL_16",
                    "Betören Anbändeln TAL_16",
                    "Betören Aufhübschen TAL_16",
                    "Betören Liebeskünste TAL_16",
                    "Betören Liebesroman TAL_16",
                    "Betören Gestaltung TAL_16",
                    "Betören Irritieren TAL_16",
                    "Einschüchtern TAL_17",
                    "Einschüchtern Drohung TAL_17",
                    "Einschüchtern Folter TAL_17",
                    "Einschüchtern Provokation TAL_17",
                    "Einschüchtern Verhör TAL_17",
                    "Etikette TAL_18",
                    "Etikette Benehmen TAL_18",
                    "Etikette Klatsch & Tratsch TAL_18",
                    "Etikette Leichte Unterhaltung TAL_18",
                    "Etikette Mode TAL_18",
                    "Etikette Heraldik & Stammbäume TAL_18",
                    "Etikette Poesie TAL_18",
                    "Etikette Dienen & Gehorchen TAL_18",
                    "Gassenwissen TAL_19",
                    "Gassenwissen Beschattung TAL_19",
                    "Gassenwissen Informationssuche TAL_19",
                    "Gassenwissen Ortseinschätzung TAL_19",
                    "Gassenwissen Kriminalgeschichten TAL_19",
                    "Menschenkenntnis TAL_20",
                    "Menschenkenntnis Lügen durchschauen TAL_20",
                    "Menschenkenntnis Motivation erkennen TAL_20",
                    "Menschenkenntnis Vorlieben erspüren TAL_20",
                    "Überreden TAL_21",
                    "Überreden Aufschwatzen TAL_21",
                    "Überreden Betteln TAL_21",
                    "Überreden Herausreden TAL_21",
                    "Überreden Manipulieren TAL_21",
                    "Überreden Schmeicheln TAL_21",
                    "Überreden Romane TAL_21",
                    "Überreden Berserker beruhigen TAL_21",
                    "Verkleiden TAL_22",
                    "Verkleiden Bühnenschauspiel TAL_22",
                    "Verkleiden Kostümierung TAL_22",
                    "Verkleiden Personen imitieren TAL_22",
                    "Willenskraft TAL_23",
                    "Willenskraft Bekehren & Überzeugen widerstehen TAL_23",
                    "Willenskraft Bedrohungen standhalten TAL_23",
                    "Willenskraft Betören widerstehen TAL_23",
                    "Willenskraft Einschüchtern widerstehen TAL_23",
                    "Willenskraft Überreden widerstehen TAL_23",
                    "Fährtensuchen TAL_24",
                    "Fährtensuchen Verwischen eigener Fährte TAL_24",
                    "Fährtensuchen Humanoide Spuren TAL_24",
                    "Fährtensuchen Tierische Spuren TAL_24",
                    "Fesseln TAL_25",
                    "Fesseln Fesselungen TAL_25",
                    "Fesseln Knotenkunde TAL_25",
                    "Fesseln Netze knüpfen TAL_25",
                    "Fesseln Seile herstellen TAL_25",
                    "Fischen & Angeln TAL_26",
                    "Fischen & Angeln Salzwassertiere TAL_26",
                    "Fischen & Angeln Süßwassertiere TAL_26",
                    "Fischen & Angeln Wasserungeheuer TAL_26",
                    "Orientierung TAL_27",
                    "Orientierung Sonnenstand TAL_27",
                    "Orientierung Sternenhimmel TAL_27",
                    "Orientierung Unter Tage TAL_27",
                    "Pflanzenkunde TAL_28",
                    "Pflanzenkunde Giftpflanzen TAL_28",
                    "Pflanzenkunde Heilpflanzen TAL_28",
                    "Pflanzenkunde Nutzpflanzen TAL_28",
                    "Pflanzenkunde Pflanzenerkennung TAL_28",
                    "Tierkunde TAL_29",
                    "Tierkunde Domestizierte Tiere TAL_29",
                    "Tierkunde Ungeheuer TAL_29",
                    "Tierkunde Wildtiere TAL_29",
                    "Wildnisleben TAL_30",
                    "Wildnisleben Feuermachen TAL_30",
                    "Wildnisleben Lageraufbau TAL_30",
                    "Wildnisleben Lagersuche TAL_30",
                    "Wildnisleben Wettervorhersage TAL_30",
                    "Brett- & Glücksspiel TAL_31",
                    "Brett- & Glücksspiel Würfelspiele TAL_31",
                    "Brett- & Glücksspiel Brettspiele TAL_31",
                    "Brett- & Glücksspiel Kartenspiele TAL_31",
                    "Brett- & Glücksspiel Wettspiele TAL_31",
                    "Brett- & Glücksspiel Fachpublikationen TAL_31",
                    "Geographie TAL_32",
                    "Geographie Albernia TAL_32",
                    "Geographie Almada TAL_32",
                    "Geographie Garetien TAL_32",
                    "Geographie Kosch TAL_32",
                    "Geographie Nordmarken TAL_32",
                    "Geographie Rommilyser Mark TAL_32",
                    "Geographie Tobrien TAL_32",
                    "Geographie Weiden TAL_32",
                    "Geographie Windhag TAL_32",
                    "Geographie Al'Anfanisches Imperium TAL_32",
                    "Geographie Andergast TAL_32",
                    "Geographie Aranien TAL_32",
                    "Geographie Bergkönigreiche der Zwerge TAL_32",
                    "Geographie Bornland TAL_32",
                    "Geographie Gjalskerland TAL_32",
                    "Geographie Hoher Norden TAL_32",
                    "Geographie Horasreich TAL_32",
                    "Geographie Kalifat TAL_32",
                    "Geographie Maraskan TAL_32",
                    "Geographie Nostria TAL_32",
                    "Geographie Orkland TAL_32",
                    "Geographie Salamandersteine & umliegende Gebiete der Elfen TAL_32",
                    "Geographie Schattenlande TAL_32",
                    "Geographie Südmeer & Waldinseln TAL_32",
                    "Geographie Svellttal TAL_32",
                    "Geographie Thorwal TAL_32",
                    "Geographie Tiefer Süden TAL_32",
                    "Geographie Tulamidenlande TAL_32",
                    "Geographie Zyklopeninseln TAL_32",
                    "Geographie Kartographie TAL_32",
                    "Geographie Fachpublikationen TAL_32",
                    "Geschichtswissen TAL_33",
                    "Geschichtswissen Albernia TAL_33",
                    "Geschichtswissen Almada TAL_33",
                    "Geschichtswissen Garetien TAL_33",
                    "Geschichtswissen Kosch TAL_33",
                    "Geschichtswissen Nordmarken TAL_33",
                    "Geschichtswissen Rommilyser Mark TAL_33",
                    "Geschichtswissen Tobrien TAL_33",
                    "Geschichtswissen Weiden TAL_33",
                    "Geschichtswissen Windhag TAL_33",
                    "Geschichtswissen Al'Anfanisches Imperium TAL_33",
                    "Geschichtswissen Andergast TAL_33",
                    "Geschichtswissen Aranien TAL_33",
                    "Geschichtswissen Bergkönigreiche der Zwerge TAL_33",
                    "Geschichtswissen Bornland TAL_33",
                    "Geschichtswissen Gjalskerland TAL_33",
                    "Geschichtswissen Hoher Norden TAL_33",
                    "Geschichtswissen Horasreich TAL_33",
                    "Geschichtswissen Kalifat TAL_33",
                    "Geschichtswissen Maraskan TAL_33",
                    "Geschichtswissen Nostria TAL_33",
                    "Geschichtswissen Orkland TAL_33",
                    "Geschichtswissen Salamandersteine & umliegende Gebiete der Elfen TAL_33",
                    "Geschichtswissen Schattenlande TAL_33",
                    "Geschichtswissen Südmeer & Waldinseln TAL_33",
                    "Geschichtswissen Svellttal TAL_33",
                    "Geschichtswissen Thorwal TAL_33",
                    "Geschichtswissen Tiefer Süden TAL_33",
                    "Geschichtswissen Tulamidenlande TAL_33",
                    "Geschichtswissen Zyklopeninseln TAL_33",
                    "Geschichtswissen Fachpublikationen TAL_33",
                    "Götter & Kulte TAL_34",
                    "Götter & Kulte Praios TAL_34",
                    "Götter & Kulte Rondra TAL_34",
                    "Götter & Kulte Efferd TAL_34",
                    "Götter & Kulte Travia TAL_34",
                    "Götter & Kulte Boron TAL_34",
                    "Götter & Kulte Hesinde TAL_34",
                    "Götter & Kulte Firun TAL_34",
                    "Götter & Kulte Tsa TAL_34",
                    "Götter & Kulte Phex TAL_34",
                    "Götter & Kulte Peraine TAL_34",
                    "Götter & Kulte Ingerimm TAL_34",
                    "Götter & Kulte Rahja TAL_34",
                    "Götter & Kulte Namenloser TAL_34",
                    "Götter & Kulte Aves TAL_34",
                    "Götter & Kulte Ifirn TAL_34",
                    "Götter & Kulte Kor TAL_34",
                    "Götter & Kulte Nandus TAL_34",
                    "Götter & Kulte Swafnir TAL_34",
                    "Götter & Kulte Marbo TAL_34",
                    "Götter & Kulte Levthan TAL_34",
                    "Götter & Kulte Rastullah TAL_34",
                    "Götter & Kulte Fachpublikationen TAL_34",
                    "Kriegskunst TAL_35",
                    "Kriegskunst Belagerung TAL_35",
                    "Kriegskunst Feldschlacht TAL_35",
                    "Kriegskunst Partisanenkampf TAL_35",
                    "Kriegskunst Seegefechte TAL_35",
                    "Kriegskunst Tunnelkampf TAL_35",
                    "Kriegskunst Fachpublikationen TAL_35",
                    "Magiekunde TAL_36",
                    "Magiekunde Artefakte TAL_36",
                    "Magiekunde Magische Wesen TAL_36",
                    "Magiekunde Rituale TAL_36",
                    "Magiekunde Zaubersprüche TAL_36",
                    "Magiekunde Fachpublikationen TAL_36",
                    "Mechanik TAL_37",
                    "Mechanik Hebel TAL_37",
                    "Mechanik Hydraulik TAL_37",
                    "Mechanik Komplexe Systeme TAL_37",
                    "Mechanik Fachpublikationen TAL_37",
                    "Mechanik Fallen herstellen TAL_37",
                    "Rechnen TAL_38",
                    "Rechnen Bruchrechnung TAL_38",
                    "Rechnen Punktrechnung TAL_38",
                    "Rechnen Strichrechnung TAL_38",
                    "Rechnen Fachpublikationen TAL_38",
                    "Rechnen Zahlenmystik TAL_38",
                    "Rechnen Verschlüsselungen TAL_38",
                    "Rechtskunde TAL_39",
                    "Rechtskunde Albernia TAL_39",
                    "Rechtskunde Almada TAL_39",
                    "Rechtskunde Garetien TAL_39",
                    "Rechtskunde Kosch TAL_39",
                    "Rechtskunde Nordmarken TAL_39",
                    "Rechtskunde Rommilyser Mark TAL_39",
                    "Rechtskunde Tobrien TAL_39",
                    "Rechtskunde Weiden TAL_39",
                    "Rechtskunde Windhag TAL_39",
                    "Rechtskunde Al'Anfanisches Imperium TAL_39",
                    "Rechtskunde Andergast TAL_39",
                    "Rechtskunde Aranien TAL_39",
                    "Rechtskunde Bergkönigreiche der Zwerge TAL_39",
                    "Rechtskunde Bornland TAL_39",
                    "Rechtskunde Gjalskerland TAL_39",
                    "Rechtskunde Hoher Norden TAL_39",
                    "Rechtskunde Horasreich TAL_39",
                    "Rechtskunde Kalifat TAL_39",
                    "Rechtskunde Maraskan TAL_39",
                    "Rechtskunde Nostria TAL_39",
                    "Rechtskunde Orkland TAL_39",
                    "Rechtskunde Salamandersteine & umliegende Gebiete der Elfen TAL_39",
                    "Rechtskunde Schattenlande TAL_39",
                    "Rechtskunde Südmeer & Waldinseln TAL_39",
                    "Rechtskunde Svellttal TAL_39",
                    "Rechtskunde Thorwal TAL_39",
                    "Rechtskunde Tiefer Süden TAL_39",
                    "Rechtskunde Tulamidenlande TAL_39",
                    "Rechtskunde Zyklopeninseln TAL_39",
                    "Rechtskunde Gildenrecht TAL_39",
                    "Rechtskunde Fachpublikationen TAL_39",
                    "Sagen & Legenden TAL_40",
                    "Sagen & Legenden Albernia TAL_40",
                    "Sagen & Legenden Almada TAL_40",
                    "Sagen & Legenden Garetien TAL_40",
                    "Sagen & Legenden Kosch TAL_40",
                    "Sagen & Legenden Nordmarken TAL_40",
                    "Sagen & Legenden Rommilyser Mark TAL_40",
                    "Sagen & Legenden Tobrien TAL_40",
                    "Sagen & Legenden Weiden TAL_40",
                    "Sagen & Legenden Windhag TAL_40",
                    "Sagen & Legenden Al'Anfanisches Imperium TAL_40",
                    "Sagen & Legenden Andergast TAL_40",
                    "Sagen & Legenden Aranien TAL_40",
                    "Sagen & Legenden Bergkönigreiche der Zwerge TAL_40",
                    "Sagen & Legenden Bornland TAL_40",
                    "Sagen & Legenden Gjalskerland TAL_40",
                    "Sagen & Legenden Hoher Norden TAL_40",
                    "Sagen & Legenden Horasreich TAL_40",
                    "Sagen & Legenden Kalifat TAL_40",
                    "Sagen & Legenden Maraskan TAL_40",
                    "Sagen & Legenden Nostria TAL_40",
                    "Sagen & Legenden Orkland TAL_40",
                    "Sagen & Legenden Salamandersteine & umliegende Gebiete der Elfen TAL_40",
                    "Sagen & Legenden Schattenlande TAL_40",
                    "Sagen & Legenden Südmeer & Waldinseln TAL_40",
                    "Sagen & Legenden Svellttal TAL_40",
                    "Sagen & Legenden Thorwal TAL_40",
                    "Sagen & Legenden Tiefer Süden TAL_40",
                    "Sagen & Legenden Tulamidenlande TAL_40",
                    "Sagen & Legenden Zyklopeninseln TAL_40",
                    "Sagen & Legenden Märchen TAL_40",
                    "Sagen & Legenden Fachpublikationen TAL_40",
                    "Sphärenkunde TAL_41",
                    "Sphärenkunde Limbus TAL_41",
                    "Sphärenkunde Sphärenwesen TAL_41",
                    "Sphärenkunde 1. Sphäre TAL_41",
                    "Sphärenkunde 2. Sphäre TAL_41",
                    "Sphärenkunde 3. Sphäre TAL_41",
                    "Sphärenkunde 4. Sphäre TAL_41",
                    "Sphärenkunde 5. Sphäre TAL_41",
                    "Sphärenkunde 6. Sphäre TAL_41",
                    "Sphärenkunde 7. Sphäre TAL_41",
                    "Sphärenkunde Fachpublikationen TAL_41",
                    "Sternkunde TAL_42",
                    "Sternkunde Astrologie TAL_42",
                    "Sternkunde Himmelskartographie TAL_42",
                    "Sternkunde Kalendarium TAL_42",
                    "Sternkunde Fachpublikationen TAL_42",
                    "Alchimie TAL_43",
                    "Alchimie Alchimistische Gifte TAL_43",
                    "Alchimie Elixiere TAL_43",
                    "Alchimie Profane Alchimie TAL_43",
                    "Boote & Schiffe TAL_44",
                    "Boote & Schiffe Kampfmanöver TAL_44",
                    "Boote & Schiffe Langstrecke TAL_44",
                    "Boote & Schiffe Verfolgungsjagden TAL_44",
                    "Boote & Schiffe Wettfahren TAL_44",
                    "Boote & Schiffe Navigation TAL_44",
                    "Fahrzeuge TAL_45",
                    "Fahrzeuge Kampfmanöver TAL_45",
                    "Fahrzeuge Langstrecke TAL_45",
                    "Fahrzeuge Verfolgungsjagden TAL_45",
                    "Fahrzeuge Wettrennen TAL_45",
                    "Handel TAL_46",
                    "Handel Buchhaltung TAL_46",
                    "Handel Feilschen TAL_46",
                    "Handel Geldwechsel TAL_46",
                    "Handel Hehlerei TAL_46",
                    "Handel Bine Maschores TAL_46",
                    "Handel Buchprüfung TAL_46",
                    "Heilkunde Gift TAL_47",
                    "Heilkunde Gift Alchimistisches Gift TAL_47",
                    "Heilkunde Gift Mineralisches Gift TAL_47",
                    "Heilkunde Gift Pflanzliches Gift TAL_47",
                    "Heilkunde Gift Tierisches Gift TAL_47",
                    "Heilkunde Krankheiten TAL_48",
                    "Heilkunde Krankheiten Flinker Difar TAL_48",
                    "Heilkunde Krankheiten Lutanas TAL_48",
                    "Heilkunde Krankheiten Rascher Wahn TAL_48",
                    "Heilkunde Krankheiten Sumpffieber/Brabaker Schweiß TAL_48",
                    "Heilkunde Krankheiten Zorganpocken TAL_48",
                    "Heilkunde Seele TAL_49",
                    "Heilkunde Seele Unterdrückung von Ängsten TAL_49",
                    "Heilkunde Seele Unterdrückung von Persönlichkeitsschwächen TAL_49",
                    "Heilkunde Seele Unterdrückung von Schlechten Eigenschaften TAL_49",
                    "Heilkunde Wunden TAL_50",
                    "Heilkunde Wunden Heilung fördern TAL_50",
                    "Heilkunde Wunden Schmerzen nehmen TAL_50",
                    "Heilkunde Wunden Stabilisieren TAL_50",
                    "Holzbearbeitung TAL_51",
                    "Holzbearbeitung Schlagen & Schneiden TAL_51",
                    "Holzbearbeitung Tischlerarbeiten TAL_51",
                    "Holzbearbeitung Zimmermannsarbeiten TAL_51",
                    "Holzbearbeitung Instrumente bauen TAL_51",
                    "Holzbearbeitung Boote bauen TAL_51",
                    "Holzbearbeitung Kutschen bauen TAL_51",
                    "Holzbearbeitung Rüstungsherstellung TAL_51",
                    "Holzbearbeitung Schiffe bauen TAL_51",
                    "Holzbearbeitung Schmuck herstellen TAL_51",
                    "Holzbearbeitung Räder herstellen TAL_51",
                    "Holzbearbeitung Waffenherstellung TAL_51",
                    "Holzbearbeitung Mechanische Konstrukte herstellen TAL_51",
                    "Lebensmittelbearbeitung TAL_52",
                    "Lebensmittelbearbeitung Ausnehmen TAL_52",
                    "Lebensmittelbearbeitung Backen TAL_52",
                    "Lebensmittelbearbeitung Braten & Sieden TAL_52",
                    "Lebensmittelbearbeitung Brauen TAL_52",
                    "Lebensmittelbearbeitung Haltbarmachung TAL_52",
                    "Lebensmittelbearbeitung Schnapsbrennen TAL_52",
                    "Lebensmittelbearbeitung Bierbrauen TAL_52",
                    "Lebensmittelbearbeitung Winzerei TAL_52",
                    "Lederbearbeitung TAL_53",
                    "Lederbearbeitung Gerben TAL_53",
                    "Lederbearbeitung Kürschnern TAL_53",
                    "Lederbearbeitung Lederwaren herstellen TAL_53",
                    "Lederbearbeitung Rüstungsherstellung TAL_53",
                    "Malen & Zeichnen TAL_54",
                    "Malen & Zeichnen Malen TAL_54",
                    "Malen & Zeichnen Ritzen TAL_54",
                    "Malen & Zeichnen Zeichnen TAL_54",
                    "Malen & Zeichnen Dokumente fälschen TAL_54",
                    "Malen & Zeichnen Zauberzeichen malen TAL_54",
                    "Malen & Zeichnen Drucken TAL_54",
                    "Malen & Zeichnen Kalligraphie TAL_54",
                    "Malen & Zeichnen Kohlezeichnungen anfertigen TAL_54",
                    "Malen & Zeichnen Kupferstich anfertigen TAL_54",
                    "Malen & Zeichnen Ölgemälde malen TAL_54",
                    "Malen & Zeichnen Tätowieren TAL_54",
                    "Malen & Zeichnen Wandmalerei anfertigen TAL_54",
                    "Metallbearbeitung TAL_55",
                    "Metallbearbeitung Feinschmiedearbeiten TAL_55",
                    "Metallbearbeitung Grobschmiedearbeiten TAL_55",
                    "Metallbearbeitung Metallguss TAL_55",
                    "Metallbearbeitung Verhütten TAL_55",
                    "Metallbearbeitung Instrumente bauen TAL_55",
                    "Metallbearbeitung Rüstungsherstellung TAL_55",
                    "Metallbearbeitung Schmuck herstellen TAL_55",
                    "Metallbearbeitung Waffenherstellung TAL_55",
                    "Metallbearbeitung Spezielle Geschosse herstellen TAL_55",
                    "Metallbearbeitung Mechanische Konstrukte herstellen TAL_55",
                    "Musizieren TAL_56",
                    "Musizieren Blasinstrumente TAL_56",
                    "Musizieren Saiteninstrumente TAL_56",
                    "Musizieren Trommeln TAL_56",
                    "Musizieren Dirigieren TAL_56",
                    "Schlösserknacken TAL_57",
                    "Schlösserknacken Bartschlösser TAL_57",
                    "Schlösserknacken Kombinationsschlösser TAL_57",
                    "Schlösserknacken Fallen entschärfen TAL_57",
                    "Schlösserknacken Fallen herstellen TAL_57",
                    "Steinbearbeitung TAL_58",
                    "Steinbearbeitung Maurerarbeiten TAL_58",
                    "Steinbearbeitung Steine brechen TAL_58",
                    "Steinbearbeitung Steinmetzarbeiten TAL_58",
                    "Steinbearbeitung Glasbläserei TAL_58",
                    "Steinbearbeitung Töpferarbeiten TAL_58",
                    "Steinbearbeitung Kristalle züchten TAL_58",
                    "Steinbearbeitung Schmuck herstellen TAL_58",
                    "Steinbearbeitung Waffenherstellung TAL_58",
                    "Steinbearbeitung Deichbau TAL_58",
                    "Steinbearbeitung Minenkenntnis TAL_58",
                    "Steinbearbeitung Bernstein verformen TAL_58",
                    "Steinbearbeitung Porzellanarbeiten TAL_58",
                    "Steinbearbeitung Mechanische Konstrukte herstellen TAL_58",
                    "Stoffbearbeitung TAL_59",
                    "Stoffbearbeitung Färben TAL_59",
                    "Stoffbearbeitung Filzen TAL_59",
                    "Stoffbearbeitung Schneidern TAL_59",
                    "Stoffbearbeitung Spinnen TAL_59",
                    "Stoffbearbeitung Weben TAL_59",
                    "Stoffbearbeitung Prunkkleider herstellen TAL_59",
                    "Stoffbearbeitung Rüstungsherstellung TAL_59",
                    "Stoffbearbeitung Mechanische Konstrukte herstellen TAL_59"]

liste_für_zauber = ["Adlerauge SPELL_1",
                    "Analys Arkanstruktur SPELL_2",
                    "Armatrutz SPELL_3",
                    "Axxeleratus SPELL_4",
                    "Balsam Salabunde SPELL_5",
                    "Bannbaladin SPELL_6",
                    "Blick in die Gedanken SPELL_7",
                    "Blitz dich find SPELL_8",
                    "Corpofesso SPELL_9",
                    "Disruptivo SPELL_10",
                    "Duplicatus SPELL_11",
                    "Falkenauge SPELL_12",
                    "Flim Flam SPELL_13",
                    "Fulminictus SPELL_14",
                    "Gardianum SPELL_15",
                    "Große Gier SPELL_16",
                    "Harmlose Gestalt SPELL_17",
                    "Hexengalle SPELL_18",
                    "Hexenkrallen SPELL_19",
                    "Horriphobus SPELL_20",
                    "Ignifaxius SPELL_21",
                    "Invocatio Minima SPELL_22",
                    "Katzenaugen SPELL_23",
                    "Krötensprung SPELL_24",
                    "Manifesto SPELL_25",
                    "Manus Miracula SPELL_26",
                    "Motoricus SPELL_27",
                    "Nebelwand SPELL_28",
                    "Oculus Illusionis SPELL_29",
                    "Odem Arcanum SPELL_30",
                    "Paralysis SPELL_31",
                    "Penetrizzel SPELL_32",
                    "Psychostabilis SPELL_33",
                    "Radau SPELL_34",
                    "Respondami SPELL_35",
                    "Salander SPELL_36",
                    "Sanftmut SPELL_37",
                    "Satuarias Herrlichkeit SPELL_38",
                    "Silentium SPELL_39",
                    "Somnigravis SPELL_40",
                    "Spinnenlauf SPELL_41",
                    "Spurlos SPELL_42",
                    "Transversalis SPELL_43",
                    "Visibili SPELL_44",
                    "Wasseratem SPELL_45",
                    "Arcanovi SPELL_46",
                    "Dschinnenruf SPELL_47",
                    "Elementarer Diener SPELL_48",
                    "Invocatio Maior SPELL_49",
                    "Invocatio Minor SPELL_50",
                    "Zauberklinge Geisterspeer SPELL_51",
                    "Ängste lindern SPELL_68",
                    "Atemnot SPELL_69",
                    "Attributo (Körperkraft) SPELL_70",
                    "Claudibus SPELL_71",
                    "Corpofrigo SPELL_72",
                    "Dunkelheit SPELL_73",
                    "Ecliptifactus SPELL_74",
                    "Große Verwirrung SPELL_75",
                    "Herr über das Tierreich SPELL_76",
                    "Hexenholz SPELL_77",
                    "Hexenknoten SPELL_78",
                    "Höllenpein SPELL_79",
                    "Ignisphaero SPELL_80",
                    "Klarum Purum SPELL_81",
                    "Pestilenz erspüren SPELL_82",
                    "Schlangenruf SPELL_83",
                    "Sensibar SPELL_84",
                    "Sumus Elixiere SPELL_85",
                    "Vipernblick SPELL_86",
                    "Zunge betäuben SPELL_87",
                    "Zwingtanz SPELL_88",
                    "Ablativum SPELL_89",
                    "Abvenenum SPELL_90",
                    "Adlerschwinge SPELL_91",
                    "Aeolito SPELL_92",
                    "Alpgestalt SPELL_93",
                    "Altisonus SPELL_94",
                    "Angst auslösen SPELL_95",
                    "Archofaxius SPELL_96",
                    "Archosphaero SPELL_97",
                    "Aromatis Illusionis SPELL_98",
                    "Attributo (Charisma) SPELL_99",
                    "Attributo (Fingerfertigkeit) SPELL_100",
                    "Attributo (Klugheit) SPELL_101",
                    "Aufwecken SPELL_102",
                    "Auge des Limbus SPELL_103",
                    "Aureolus SPELL_104",
                    "Auris Illusionis SPELL_105",
                    "Band und Fessel SPELL_106",
                    "Blick aufs Wesen SPELL_107",
                    "Blindheit SPELL_108",
                    "Chamaelioni SPELL_109",
                    "Dämonenbann SPELL_110",
                    "Dämonenschild SPELL_111",
                    "Debilitatio SPELL_112",
                    "Desintegratus SPELL_113",
                    "Einflussbann SPELL_114",
                    "Eisenrost SPELL_115",
                    "Elementarbann SPELL_116",
                    "Elfenstimme SPELL_117",
                    "Erinnerung verlasse dich SPELL_118",
                    "Exposami SPELL_119",
                    "Favilludo SPELL_120",
                    "Fischflosse SPELL_121",
                    "Foramen SPELL_122",
                    "Fortifex SPELL_123",
                    "Gedankenbilder SPELL_124",
                    "Gefunden SPELL_125",
                    "Haselbusch SPELL_126",
                    "Heilungsbann SPELL_127",
                    "Hellsichtbann SPELL_128",
                    "Heptagramma SPELL_129",
                    "Herzschlag ruhe SPELL_130",
                    "Hexagramma SPELL_131",
                    "Ignorantia SPELL_132",
                    "Illusionsbann SPELL_133",
                    "Imperavi SPELL_134",
                    "Impersona SPELL_135",
                    "Incendio SPELL_136",
                    "Invercano SPELL_137",
                    "Karnifilo SPELL_138",
                    "Kusch SPELL_139",
                    "Last des Alters SPELL_140",
                    "Lunge des Leviatan SPELL_141",
                    "Manus Illusionis SPELL_142",
                    "Memorans SPELL_143",
                    "Menetekel SPELL_144",
                    "Nuntiovolo SPELL_145",
                    "Objectobscuro SPELL_146",
                    "Objectofixo SPELL_147",
                    "Objektbann SPELL_148",
                    "Oculus Astralis SPELL_149",
                    "Orcanofaxius SPELL_150",
                    "Orcanosphaero SPELL_151",
                    "Pentagramma SPELL_152",
                    "Physiostablis SPELL_153",
                    "Plumbumbarum SPELL_154",
                    "Projectimago SPELL_155",
                    "Reflectimago SPELL_156",
                    "Regeneratio SPELL_157",
                    "Sapefacta SPELL_158",
                    "Schmerzen lindern SPELL_159",
                    "Schwarz und Rot SPELL_160",
                    "Schwarzer Schrecken SPELL_161",
                    "Skelettarius SPELL_162",
                    "Solidirid SPELL_163",
                    "Taubheit SPELL_164",
                    "Telekinesebann SPELL_165",
                    "Tiergedanken SPELL_166",
                    "Verwandlungsbann SPELL_167",
                    "Vogelzwitschern SPELL_168",
                    "Wolfstatze SPELL_169",
                    "Caldofrigo SPELL_170",
                    "Nihilogravo SPELL_171",
                    "Accuratum SPELL_172",
                    "Hagelschlag und Sturmgebrüll SPELL_173",
                    "Hartes schmelze SPELL_174",
                    "Leidensbund SPELL_175",
                    "Magischer Raub SPELL_176",
                    "Memorabia Falsifir SPELL_177",
                    "Movimento SPELL_178",
                    "Ruhe Körper SPELL_179",
                    "Unberührt von Satinav SPELL_180",
                    "Widerwille SPELL_181",
                    "Wirbelform SPELL_182",
                    "Xenographus SPELL_183",
                    "Affenarme SPELL_234",
                    "Affenruf SPELL_235",
                    "Arachnea SPELL_236",
                    "Attributo (Gewandheit) SPELL_237",
                    "Attributo (Intuition) SPELL_238",
                    "Attributo (Mut) SPELL_239",
                    "Attributo (Konstitution) SPELL_240",
                    "Avilea SPELL_241",
                    "Basaltleib SPELL_242",
                    "Brandungsleib SPELL_243",
                    "Brennender Hass SPELL_244",
                    "Dämonisches Vergessen SPELL_245",
                    "Drachenleib SPELL_246",
                    "Eichenleib SPELL_247",
                    "Eigene Ängste SPELL_248",
                    "Eigene Dummheit SPELL_249",
                    "Eispfeil SPELL_250",
                    "Erzpfeil SPELL_251",
                    "Eulenruf SPELL_252",
                    "Federleib SPELL_253",
                    "Feenstaub SPELL_254",
                    "Feuerpfeil SPELL_255",
                    "Firnlauf SPELL_256",
                    "Flammenwand SPELL_257",
                    "Fledermausruf SPELL_258",
                    "Frostleib SPELL_259",
                    "Geisteressenz SPELL_260",
                    "Gifthaut SPELL_261",
                    "Glutlauf SPELL_262",
                    "Hexenspeichel SPELL_263",
                    "Hilfreiche Pfote SPELL_264",
                    "Hilfreiche Schwinge SPELL_265",
                    "Hilfreiche Tatze SPELL_266",
                    "Himmelslauf SPELL_267",
                    "Hornissenruf SPELL_268",
                    "Humuspfeil SPELL_269",
                    "Katzenruf SPELL_270",
                    "Krabbelnder Schrecken SPELL_271",
                    "Krähenruf SPELL_272",
                    "Kraft des Tieres SPELL_273",
                    "Kulminatio SPELL_274",
                    "Levthans Feuer SPELL_275",
                    "Luftpfeil SPELL_276",
                    "Mal der Erschöpfung SPELL_277",
                    "Mal der Schwäche SPELL_278",
                    "Objectovoco SPELL_279",
                    "Pandaemonium SPELL_280",
                    "Pestodem SPELL_281",
                    "Reptilea SPELL_282",
                    "Sanfter Fall SPELL_283",
                    "Schlechte Ausstrahlung SPELL_284",
                    "Schleier der Unwissenheit SPELL_285",
                    "Seelentier erkennen SPELL_286",
                    "Seidenzunge SPELL_287",
                    "Serpentialis SPELL_288",
                    "Spinnenruf SPELL_289",
                    "Standfest SPELL_290",
                    "Steinwand SPELL_291",
                    "Tiere besprechen SPELL_292",
                    "Unentflammbarkeit SPELL_293",
                    "Ungeschickt SPELL_294",
                    "Verunsicherung SPELL_295",
                    "Wasserpfeil SPELL_296",
                    "Weiches Erstarre SPELL_297",
                    "Welle der Reinigung SPELL_298",
                    "Welle des Schmerzes SPELL_299",
                    "Wellenlauf SPELL_300",
                    "Wipfellauf SPELL_301",
                    "Wüstenlauf SPELL_302",
                    "Zauberpferd herbeirufen SPELL_303",
                    "Adamantium SPELL_304",
                    "Animatio SPELL_305",
                    "Band der Freundschaft SPELL_306",
                    "Bärenruhe SPELL_307",
                    "Blick in die Vergangenheit SPELL_308",
                    "Brandform SPELL_309",
                    "Custodosigil SPELL_310",
                    "Destructibo SPELL_311",
                    "Eins mit der Natur SPELL_312",
                    "Ergebenheit der Wogen SPELL_313",
                    "Erhabenheit des Marmors SPELL_314",
                    "Felsenform SPELL_315",
                    "Freiheit der Wolken SPELL_316",
                    "Geisterruf SPELL_317",
                    "Geisterbeschwörung SPELL_318",
                    "Gletscherform SPELL_319",
                    "Klarheit des Eises SPELL_320",
                    "Körperlose Reise SPELL_321",
                    "Madas Spiegel SPELL_322",
                    "Nekropathia SPELL_323",
                    "Pflanzenform SPELL_324",
                    "Reinheit der Lohe SPELL_325",
                    "Ruf der Feenwesen SPELL_326",
                    "Seelenwanderung SPELL_327",
                    "Standhafter Wächter SPELL_328",
                    "Transmutare SPELL_329",
                    "Traumgestalt SPELL_330",
                    "Überlegener Krieger SPELL_331",
                    "Weisheit der Bäume SPELL_332",
                    "Wogenform SPELL_334",
                    "Zaubernahrung SPELL_335",
                    "Zauberschnurren SPELL_336",
                    "Zauberwesen der Natur SPELL_337",
                    "Zauberzwang SPELL_338",
                    "Begehren erzeugen SPELL_386",
                    "Brustformung SPELL_387",
                    "Erregung spüren SPELL_388",
                    "Feuchte Erregung SPELL_389",
                    "Penisformung SPELL_391",
                    "Spielzeug der Lust SPELL_392",
                    "Vaginaformung SPELL_393",
                    "Verlangen kontrollieren SPELL_394",
                    "Abneigungen und Vorlieben erzeugen SPELL_395",
                    "Begierde auslösen SPELL_396",
                    "Übertragung der Liebeskünste SPELL_397",
                    "Dämonenpakt beenden SPELL_402",
                    "Aquafaxius SPELL_403",
                    "Aquasphaero SPELL_404",
                    "Aura der Erschöpfung SPELL_405",
                    "Blitzball SPELL_406",
                    "Böser Blick SPELL_407",
                    "Dornenwand SPELL_408",
                    "Eiswand SPELL_409",
                    "Erschöpfungen lindern SPELL_410",
                    "Fesselfeld SPELL_411",
                    "Frigifaxius SPELL_412",
                    "Frigisphaero SPELL_413",
                    "Halluzination SPELL_414",
                    "Humofaxius SPELL_415",
                    "Humosphaero SPELL_416",
                    "Invinculo SPELL_417",
                    "Nebelform SPELL_418",
                    "Oktagramma SPELL_419",
                    "Panik überkomme euch SPELL_420",
                    "Schimmernder Schild SPELL_421",
                    "Schuppenhaut SPELL_422",
                    "Sphärenbann SPELL_423",
                    "Sinesigil SPELL_424",
                    "Sensattacco SPELL_425",
                    "Stillstand SPELL_426",
                    "Sturm der Verunsicherung SPELL_427",
                    "Sturmwand SPELL_428",
                    "Temporalbann SPELL_429",
                    "Tempus Stasis SPELL_430",
                    "Wellenwand SPELL_431",
                    "Woge der Versteinerung SPELL_432",
                    "Zorn der Elemente SPELL_433",
                    "Zweifel schüren SPELL_434",
                    "Applicatus SPELL_435",
                    "Blick durch fremde Augen SPELL_436",
                    "Chimaeroform SPELL_437",
                    "Chronoklassis SPELL_438",
                    "Chrononautos SPELL_439",
                    "Gefäß der Jahre SPELL_440",
                    "Immortalis Lebenszeit SPELL_441",
                    "Invocatio Maxima SPELL_442",
                    "Infinitum Immerdar SPELL_443",
                    "Meister der Elemente SPELL_444",
                    "Lawinenfall und Trümmerfeld SPELL_445",
                    "Planastrale SPELL_446",
                    "Stein wandle SPELL_447",
                    "Totes handle SPELL_448",
                    "Zitterfinger SPELL_483"]

liste_für_Liturgien = ["Bann der Dunkelheit LITURGY_1",
                       "Bann der Furcht LITURGY_2",
                       "Bann des Lichts LITURGY_3",
                       "Blendstrahl LITURGY_4",
                       "Ehrenhaftigkeit LITURGY_5",
                       "Entzifferung LITURGY_6",
                       "Ermutigung LITURGY_7",
                       "Fall ins Nichts LITURGY_8",
                       "Friedvolle Aura LITURGY_9",
                       "Giftbann LITURGY_10",
                       "Göttlicher Fingerzeig LITURGY_11",
                       "Göttliches Zeichen LITURGY_12",
                       "Heilsegen LITURGY_13",
                       "Kleiner Bann wider Untote LITURGY_14",
                       "Kleiner Bannstrahl LITURGY_15",
                       "Krankheitsbann LITURGY_16",
                       "Lautlos LITURGY_17",
                       "Magieschutz LITURGY_18",
                       "Magiesicht LITURGY_19",
                       "Mondsicht LITURGY_20",
                       "Mondsilberzunge LITURGY_21",
                       "Objektsegen LITURGY_22",
                       "Ort der Ruhe LITURGY_23",
                       "Pflanzenwuchs LITURGY_24",
                       "Rabenruf LITURGY_25",
                       "Schlaf LITURGY_26",
                       "Schlangenstab LITURGY_27",
                       "Schlangenzunge LITURGY_28",
                       "Schmerzresistenz LITURGY_29",
                       "Schutz der Wehrlosen LITURGY_30",
                       "Sternenglanz LITURGY_31",
                       "Wahrheit LITURGY_32",
                       "Wieselflink LITURGY_33",
                       "Wundersame Verständigung LITURGY_34",
                       "Ackersegen LITURGY_35",
                       "Exorzismus LITURGY_36",
                       "Geweihter Panzer LITURGY_37",
                       "Löwengestalt LITURGY_38",
                       "Nebelleib LITURGY_39",
                       "Objektweihe LITURGY_40",
                       "Angriffslust LITURGY_41",
                       "Angriffswelle LITURGY_42",
                       "Auge des Jägers LITURGY_43",
                       "Bann der göttlichen Gaben LITURGY_44",
                       "Bann wider Untote LITURGY_45",
                       "Bannstrahl LITURGY_46",
                       "Befreiung des Geistes LITURGY_47",
                       "Begnadeter Reiter LITURGY_48",
                       "Besänftigung LITURGY_49",
                       "Bescheidenheit LITURGY_50",
                       "Beschwörung der gemeinen Diener des Rattenkindes LITURGY_51",
                       "Blendung LITURGY_52",
                       "Blick des Heilers LITURGY_53",
                       "Blitzschlag LITURGY_54",
                       "Blutiger Zorn LITURGY_55",
                       "Blutzoll LITURGY_56",
                       "Bodenweihe LITURGY_57",
                       "Dämonenwall LITURGY_58",
                       "Delphinruf LITURGY_59",
                       "Des Einen bezaubernder Sphärenklang LITURGY_60",
                       "Ehrlicher Vertrag LITURGY_61",
                       "Entfesselung LITURGY_62",
                       "Erdbeben LITURGY_63",
                       "Ernüchterung LITURGY_64",
                       "Erzene Opfergabe LITURGY_65",
                       "Feuerwall LITURGY_66",
                       "Friedfertigkeit LITURGY_67",
                       "Friedvoller Rausch LITURGY_68",
                       "Froststurm LITURGY_69",
                       "Gebieter der Flammen LITURGY_70",
                       "Geisterblick LITURGY_71",
                       "Gesegneter Rausch LITURGY_72",
                       "Getreidewachstum LITURGY_73",
                       "Goldene Hand LITURGY_74",
                       "Goldene Rüstung LITURGY_75",
                       "Göttliche Klinge LITURGY_76",
                       "Göttliche Verständigung LITURGY_77",
                       "Heiliger Befehl LITURGY_78",
                       "Heiliges Liebesspiel LITURGY_79",
                       "Heilsame Quelle LITURGY_80",
                       "Heldenkraft LITURGY_81",
                       "Helfende Hand LITURGY_82",
                       "Herbeirufung der Heerscharen des Rattenkindes (Ratten) LITURGY_83",
                       "Herbeirufung der Heerscharen des Rattenkindes (Schakale) LITURGY_84",
                       "Herbeirufung der Heerscharen des Rattenkindes (Vampirfledermäuse) LITURGY_85",
                       "Herbeirufung der Heerscharen des Rattenkindes (Wolfsspinnen) LITURGY_86",
                       "Herr der Flammen LITURGY_87",
                       "Hilfreiche Seele LITURGY_88",
                       "Innere Ruhe LITURGY_89",
                       "Klarer Geist LITURGY_90",
                       "Kleine Windhose LITURGY_91",
                       "Lebensschutz LITURGY_92",
                       "Liturgieschild LITURGY_93",
                       "Mächtiger Angriff LITURGY_94",
                       "Magiebann LITURGY_95",
                       "Magiespiegel LITURGY_96",
                       "Maske LITURGY_97",
                       "Mit Dummheit schlagen LITURGY_98",
                       "Motivation LITURGY_99",
                       "Namenlose Kälte LITURGY_100",
                       "Namenlose Raserei LITURGY_101",
                       "Namenlose Zweifel LITURGY_102",
                       "Namenloses Vergessen LITURGY_103",
                       "Obsession LITURGY_104",
                       "Offenlegung des Geistes LITURGY_105",
                       "Opfergang LITURGY_106",
                       "Pech und Schwefel LITURGY_107",
                       "Rattenschwarm LITURGY_108",
                       "Ruf der Heimat LITURGY_109",
                       "Schleichende Fäulnis LITURGY_110",
                       "Schutzsegen LITURGY_111",
                       "Schwindende Zauberkraft LITURGY_112",
                       "Seelenschatten LITURGY_113",
                       "Seevogelsprache LITURGY_114",
                       "Sicherer Weg LITURGY_115",
                       "Sturmruf LITURGY_116",
                       "Tiere beruhigen LITURGY_117",
                       "Tierleid lindern LITURGY_118",
                       "Tiersprache LITURGY_119",
                       "Treuer Begleiter LITURGY_120",
                       "Unterwasseratmung LITURGY_121",
                       "Versteinerung LITURGY_122",
                       "Wasserlauf LITURGY_123",
                       "Windhose LITURGY_124",
                       "Windruf LITURGY_125",
                       "Zähe Haut LITURGY_126",
                       "Ächtung (Exkommunikation) LITURGY_127",
                       "Aufnahme (Initiation) LITURGY_128",
                       "Ausbrennen (Purgation) LITURGY_129",
                       "Bannfluch (Anathema) LITURGY_130",
                       "Berauschender Wein LITURGY_131",
                       "Beschwörung der hohen Diener des Rattenkindes LITURGY_132",
                       "Beschwörung der machtvollen Diener des Rattenkindes LITURGY_133",
                       "Bild für die Ewigkeit LITURGY_134",
                       "Blick in die Flammen LITURGY_135",
                       "Delphingestalt LITURGY_136",
                       "Eidechsengestalt LITURGY_137",
                       "Eisbärgestalt LITURGY_138",
                       "Erinnern LITURGY_139",
                       "Fest der Freude LITURGY_140",
                       "Frostschutz LITURGY_141",
                       "Fruchtbarkeit LITURGY_142",
                       "Fuchsgestalt LITURGY_143",
                       "Gänsegestalt LITURGY_144",
                       "Geschwinder Schritt LITURGY_145",
                       "Göttliche Erkenntnis LITURGY_146",
                       "Greifenruf LITURGY_147",
                       "Guter Fang LITURGY_148",
                       "Häutung LITURGY_149",
                       "Heiliger Schwur LITURGY_150",
                       "Herr der Meere LITURGY_151",
                       "Hilfe in der Not LITURGY_152",
                       "Inspiration LITURGY_153",
                       "Jagdglück LITURGY_154",
                       "Jugendlichkeit LITURGY_155",
                       "Kleine Moralstärkung LITURGY_156",
                       "Läuterung des Erzes LITURGY_157",
                       "Liturgieabsorption LITURGY_158",
                       "Makelloser Leib LITURGY_159",
                       "Metallerhitzung LITURGY_160",
                       "Moralstärkung LITURGY_161",
                       "Nahrungsreinigung LITURGY_162",
                       "Nebelschwaden LITURGY_163",
                       "Ortsweihe (Sanctum) LITURGY_164",
                       "Panthergestalt LITURGY_165",
                       "Paradiesvogelgestalt LITURGY_166",
                       "Pferdegestalt LITURGY_167",
                       "Priesterweihe (Ordination) LITURGY_168",
                       "Rabengestalt LITURGY_169",
                       "Reisesegen LITURGY_170",
                       "Sättigung LITURGY_171",
                       "Schlangengestalt LITURGY_172",
                       "Schwanengestalt LITURGY_173",
                       "Seelenbannung LITURGY_174",
                       "Seelenprüfung LITURGY_175",
                       "Segnung des Heims LITURGY_176",
                       "Sicherer Tritt LITURGY_177",
                       "Speisung LITURGY_178",
                       "Staub und Schimmel LITURGY_179",
                       "Storchengestalt LITURGY_180",
                       "Tempelweihe (Konsekration) LITURGY_181",
                       "Traumbild LITURGY_182",
                       "Unbeschwerte Wanderung LITURGY_183",
                       "Verblassende Erinnerung LITURGY_184",
                       "Vergessen LITURGY_185",
                       "Waffenfluch LITURGY_186",
                       "Wegweiser LITURGY_187",
                       "Weihe des Heims LITURGY_188",
                       "Wiederherstellung LITURGY_189",
                       "Winterschlaf LITURGY_190",
                       "Zuflucht LITURGY_191",
                       "Zwergwalgestalt LITURGY_192",
                       "Blick auf den Meeresgrund LITURGY_193",
                       "Botschaft aus der Tiefe LITURGY_194",
                       "Ertrinken LITURGY_195",
                       "Furchtresistenz LITURGY_196",
                       "Numinorus Fesseln LITURGY_197",
                       "Quallenhaut LITURGY_198",
                       "Quallenruf LITURGY_199",
                       "Schiffsgespür LITURGY_200",
                       "Unsichtbare Flut LITURGY_201",
                       "Leitende Strömung LITURGY_202",
                       "Numinorus Fluch LITURGY_203",
                       "Schattenrochengestalt LITURGY_204",
                       "Seemonsterruf LITURGY_205",
                       "Empfängnisverhütung LITURGY_206",
                       "Entstelltes Antlitz LITURGY_207",
                       "Erregender Rausch LITURGY_208",
                       "Erregung kontrollieren LITURGY_209",
                       "Fesselndes Band LITURGY_210",
                       "Gespiegelte Gefühle LITURGY_211",
                       "Gigantische Geilheit LITURGY_212",
                       "Hand der Lust LITURGY_213",
                       "Heiliges Liebesspiel LITURGY_214",
                       "Hastiger Höhepunkt LITURGY_215",
                       "Krankheitsvorbeugung LITURGY_216",
                       "Verstecktes Begehren LITURGY_218",
                       "Einflüsterung LITURGY_219",
                       "Geschlechterwechsel LITURGY_220",
                       "Heiliger Höhepunkt LITURGY_221",
                       "Körper der Radscha Uschtammar LITURGY_222",
                       "Liebesschlaf LITURGY_223",
                       "Liebestätowierung LITURGY_224",
                       "Lusttrank LITURGY_225",
                       "Dämonenpakt brechen LITURGY_226",
                       "Steinhaut LITURGY_227",
                       "Schaffenskraft LITURGY_228"]
